services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD} 
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql  # Persist database data
    ports:
      - "3307:3306"

  init:
    container_name: mysql-init
    build:
      context: ./init
    volumes:
      - /tmp/mysql:/usr/lib/mysql
      - /tmp/shared:/usr/lib/shared
    env_file:
      - .env
    environment:
      - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  web:
    container_name: django-container
    build: 
      context: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_HOST=${SQL_HOST}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_PORT=${SQL_PORT}  
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
